### ISSUE TITLE
CAN

### ISSUE THREAD

**Issue by RudolphRiedel** [adafruit/Adafruit-Feather-M4-CAN-PCB#1]
Hello,

the TCAN1051HGV you are using is "only" rated for 5MBit/s.
You might like to checkout the TCAN1044V which is rated for8MBit/s, comes in SOT23-8 and is a little less expensive.

https://www.ti.com/product/TCAN1044V
https://www.ti.com/product/TCAN1044V-Q1

I designed the hardware for an USB/CAN interface with two isolated CAN channels based on the ATSAME51J19A  a while ago:
https://github.com/RudolphRiedel/USB_CAN-FD

**Comment by ladyada** [comment]
thankx will look! the dev board uses the AT6561 which is also only 5 mbs!
https://www.microchip.com/wwwproducts/en/ata6561

**Comment by ashishsk** [comment]
Hi, 

I have purchased the board and I am curious to check its features. However, I could not find the libraries or examples. Could you link me to them? 

Thanks!

Edit: oops, I intended to post this as a new issue and somehow got stuck here.

**Comment by RudolphRiedel** [comment]
I have no use for it as I wrote my own CAN driver for the E51 but after a quick look around I would assume it is this one: https://github.com/adafruit/arduino-CAN
