### ISSUE TITLE
Library support

### ISSUE THREAD

**Issue by ashishsk** [adafruit/Adafruit-Feather-M4-CAN-PCB#2]
Hi,

I have purchased the board and I am curious to check its features. However, I could not find the libraries or examples. Could you link me to them?

Thanks!

**Comment by evaherrada** [comment]
Hey! Here's a guide for the built-in CircuitPython library: https://learn.adafruit.com/using-canio-circuitpython
The docs for the CircuitPython library can be found here: https://circuitpython.readthedocs.io/en/6.0.x/shared-bindings/canio/index.html

If you're looking to use it with Arduino, here's that library: https://github.com/adafruit/arduino-CAN
The Arduino library doesn't say it's compatible with that specific board, but I think it might work

**Comment by ashishsk** [comment]
@dherrada Thanks for the links, Dylan. I am trying out the Arduino library and the adafruit fork repo doesn't compile even though it seems like the support for Feather M4 CAN has been added. The error that I am currently encountering is of a missing same51.h. 
Any idea if this can be resolved?

**Comment by evaherrada** [comment]
@ashishsk I'd open an issue on that library. I rarely work with Arduino so I'm not really sure how to help

**Comment by ladyada** [comment]
hi thanks for being patient! please check out
https://learn.adafruit.com/adafruit-feather-m4-can-express
for deets. if you need more help please open an issue on the the https://github.com/adafruit/arduino-CAN library, submit a 'feedback' on learning system or post in adafruit forums :)

**Comment by ashishsk** [comment]
Thanks for the reply. I have taken your suggestion and did all 3 of them
because that's how important and urgent it is for me to solve this issue. I
bought 10 of these boards on the first release order and I really want to
put it to use since it was a huge investment for me. I hope this issue is
resolved at the earliest.

Regards,
Ashish
