### ISSUE TITLE
no learning guide / no examples / no CAN-library / strange neopixel handling in HW & SW

### ISSUE THREAD

**Issue by BlackBrix** [adafruit/Adafruit-Feather-M4-CAN-PCB#3]
I bought the Adafruit the Feather M4 CAN in December,
BUT:
When will there be support for the Feather M4 CAN, cause up to now (01-25-2021):
- there's no learning guide so far
- there's no arduino CAN library for the ATSAME51J19 from adafruit (so far) [MCP2515 based only]
- the uf2-bootloader has errors in regards of displaying the correct bootloader status via the neopixel LED
- the arduino package has errors as well in regards of correct Pin-assignment the neopixel PWR Pin
- the neopixel draws way too much current out from the MCU-Output-Pin (MCU-Output-Pin Voltage drops from 3.3V to 2.7V) [an additional FET would be the much better solution as done already on other feather boards]

see as well these forum topics (regarding this 5 issues above):
 - https://forums.adafruit.com/viewtopic.php?f=57&t=174012
 - https://forums.adafruit.com/viewtopic.php?f=57&t=173723

very disappointing customer-experience so far ... :-/

**Comment by ladyada** [comment]
yeah its been an 'exciting' few weeks - normally does not take this long! guide is being worked on today :)

**Comment by ladyada** [comment]
hi thanks for being patient! please check out
https://learn.adafruit.com/adafruit-feather-m4-can-express
for deets. if you need more help please open an issue on the the https://github.com/adafruit/arduino-CAN library, submit a 'feedback' on learning system or post in adafruit forums :)
